create table if not exists visit_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ip_hash text not null,
  page_path text not null default '',
  referrer text not null default '',
  user_agent text not null default '',
  language text not null default '',
  country text not null default '',
  region text not null default '',
  city text not null default ''
);

alter table visit_events enable row level security;
drop policy if exists "no public reads" on visit_events;
